/*******************************************************************************
 * Copyright (c) 2014, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @header      UTI.h
 * @copyright   (c) 2014 - Jean-David Gadina - www.xs-labs.com
 * @abstract    Objective-C wrapper class for Uniform Type Identifiers (UTIs)
 */

#ifndef NS_DESIGNATED_INITIALIZER
#define NS_DESIGNATED_INITIALIZER
#endif

typedef NS_ENUM( NSInteger, UTITagClass )
{
    UTITagClassFilenameExtension    = 0x00,
    UTITagClassMIMEType             = 0x01,
    UTITagClassNSPboardType         = 0x02,
    UTITagClassOSType               = 0x03
};

typedef NS_ENUM( NSInteger, UTIDeclarationDictionaryKey )
{
    UTIDeclarationDictionaryKeyExportedType     = 0x00,
    UTIDeclarationDictionaryKeyImportedType     = 0x01,
    UTIDeclarationDictionaryKeyIdentifier       = 0x02,
    UTIDeclarationDictionaryKeyTagSpecification = 0x03,
    UTIDeclarationDictionaryKeyConformsTo       = 0x04,
    UTIDeclarationDictionaryKeyDescription      = 0x05,
    UTIDeclarationDictionaryKeyIconFile         = 0x06,
    UTIDeclarationDictionaryKeyReferenceURL     = 0x07,
    UTIDeclarationDictionaryKeyVersion          = 0x08
};

@interface UTI: NSObject < NSCopying >

@property ( nonatomic, readonly ) NSString * preferredFilenameExtension;
@property ( nonatomic, readonly ) NSString * preferredMIMEType;
@property ( nonatomic, readonly ) NSString * preferredNSPboardType;
@property ( nonatomic, readonly ) NSString * preferredOSType;
@property ( nonatomic, readonly ) NSString * description;
@property ( nonatomic, readonly ) NSDictionary * declaration;
@property ( nonatomic, readonly ) NSURL * declaringBundleURL;
@property ( nonatomic, readonly ) NSArray * exportedTypes;
@property ( nonatomic, readonly ) NSArray * importedTypes;
@property ( nonatomic, readonly ) NSString * identifier;
@property ( nonatomic, readonly ) NSDictionary * tagSpecifications;
@property ( nonatomic, readonly ) NSArray * conformsTo;
@property ( nonatomic, readonly ) NSString * iconFile;
@property ( nonatomic, readonly ) NSURL * referenceURL;
@property ( nonatomic, readonly ) NSString * version;
+ ( instancetype )UTIWithString: ( NSString * )str;
+ ( instancetype )UTIWithCFString: ( CFStringRef )str;
+ ( instancetype )UTIWithFileExtension: ( NSString * )extension;
+ ( instancetype )UTIWithFileExtension: ( NSString * )extension conformingTo: ( UTI * )uti;
+ ( instancetype )UTIWithMIMEType: ( NSString * )type;
+ ( instancetype )UTIWithMIMEType: ( NSString * )type conformingTo: ( UTI * )uti;
+ ( instancetype )UTIWithNSPboardType: ( NSString * )type;
+ ( instancetype )UTIWithNSPboardType: ( NSString * )type conformingTo: ( UTI * )uti;
+ ( instancetype )UTIWithOSType: ( NSString * )type;
+ ( instancetype )UTIWithOSType: ( NSString * )type conformingTo: ( UTI * )uti;
+ ( instancetype )UTIWithTag: ( NSString * )tag tagClass: ( UTITagClass )tagClass conformingTo: ( UTI * )uti;
+ ( NSArray * )abstractTypes;
+ ( NSArray * )concreteTypes;
+ ( NSArray * )compositeContentTypes;
+ ( NSArray * )imageContentTypes;
+ ( NSArray * )audioVisualContentTypes;
+ ( NSArray * )directoryTypes;
+ ( NSArray * )applicationTypes;
+ ( NSArray * )miscellaneousTypes;
+ ( instancetype )itemTypeUTI;
+ ( instancetype )contentTypeUTI;
+ ( instancetype )compositeContentTypeUTI;
+ ( instancetype )applicationTypeUTI;
+ ( instancetype )messageTypeUTI;
+ ( instancetype )contactTypeUTI;
+ ( instancetype )archiveTypeUTI;
+ ( instancetype )diskImageTypeUTI;
+ ( instancetype )dataTypeUTI;
+ ( instancetype )directoryTypeUTI;
+ ( instancetype )resolvableTypeUTI;
+ ( instancetype )symLinkTypeUTI;
+ ( instancetype )mountPointTypeUTI;
+ ( instancetype )aliasFileTypeUTI;
+ ( instancetype )aliasRecordTypeUTI;
+ ( instancetype )URLTypeUTI;
+ ( instancetype )fileURLTypeUTI;
+ ( instancetype )textTypeUTI;
+ ( instancetype )plainTextTypeUTI;
+ ( instancetype )UTF8PlainTextTypeUTI;
+ ( instancetype )UTF16ExternalPlainTextTypeUTI;
+ ( instancetype )UTF16PlainTextTypeUTI;
+ ( instancetype )RTFTypeUTI;
+ ( instancetype )HTMLTypeUTI;
+ ( instancetype )XMLTypeUTI;
+ ( instancetype )sourceCodeTypeUTI;
+ ( instancetype )CSourceTypeUTI;
+ ( instancetype )objectiveCSourceTypeUTI;
+ ( instancetype )CPlusPlusSourceTypeUTI;
+ ( instancetype )objectiveCPlusPlusSourceTypeUTI;
+ ( instancetype )CHeaderTypeUTI;
+ ( instancetype )CPlusPlusHeaderTypeUTI;
+ ( instancetype )javaSourceTypeUTI;
+ ( instancetype )PDFTypeUTI;
+ ( instancetype )RTFDTypeUTI;
+ ( instancetype )flatRTFDTypeUTI;
+ ( instancetype )TXNTextAndMultimediaDataTypeUTI;
+ ( instancetype )webArchiveTypeUTI;
+ ( instancetype )imageTypeUTI;
+ ( instancetype )JPEGTypeUTI;
+ ( instancetype )JPEG2000TypeUTI;
+ ( instancetype )TIFFTypeUTI;
+ ( instancetype )PICTTypeUTI;
+ ( instancetype )GIFTypeUTI;
+ ( instancetype )PNGTypeUTI;
+ ( instancetype )quickTimeImageTypeUTI;
+ ( instancetype )appleICNS;
+ ( instancetype )BMPTypeUTI;
+ ( instancetype )ICOTypeUTI;
+ ( instancetype )audiovisualContentTypeUTI;
+ ( instancetype )movieTypeUTI;
+ ( instancetype )videoTypeUTI;
+ ( instancetype )audioTypeUTI;
+ ( instancetype )quickTimeMovieTypeUTI;
+ ( instancetype )MPEGTypeUTI;
+ ( instancetype )MPEG4TypeUTI;
+ ( instancetype )MP3TypeUTI;
+ ( instancetype )MPEG4AudioTypeUTI;
+ ( instancetype )appleProtectedMPEG4AudioTypeUTI;
+ ( instancetype )folderTypeUTI;
+ ( instancetype )volumeTypeUTI;
+ ( instancetype )packageTypeUTI;
+ ( instancetype )bundleTypeUTI;
+ ( instancetype )frameworkTypeUTI;
+ ( instancetype )applicationBundleTypeUTI;
+ ( instancetype )applicationFileTypeUTI;
+ ( instancetype )vCardTypeUTI;
+ ( instancetype )inkTextTypeUTI;
+ ( NSArray * )allUTIsWithFileExtension: ( NSString * )extension;
+ ( NSArray * )allUTIsWithFileExtension: ( NSString * )extension conformingTo: ( UTI * )uti;
+ ( NSArray * )allUTIsWithMIMEType: ( NSString * )type;
+ ( NSArray * )allUTIsWithMIMEType: ( NSString * )type conformingTo: ( UTI * )uti;
+ ( NSArray * )allUTIsWithNSPboardType: ( NSString * )type;
+ ( NSArray * )allUTIsWithNSPboardType: ( NSString * )type conformingTo: ( UTI * )uti;
+ ( NSArray * )allUTIsWithOSType: ( NSString * )type;
+ ( NSArray * )allUTIsWithOSType: ( NSString * )type conformingTo: ( UTI * )uti;
+ ( NSArray * )allUTIsWithTag: ( NSString * )tag tagClass: ( UTITagClass )tagClass conformingTo: ( UTI * )uti;
+ ( NSString * )stringForOSType: ( OSType )type;
+ ( OSType )OSTypeForString: ( NSString * )str;
- ( instancetype )initWithString: ( NSString * )str;
- ( instancetype )initWithCFString: ( CFStringRef )str NS_DESIGNATED_INITIALIZER;
- ( instancetype )initWithFileExtension: ( NSString * )extension;
- ( instancetype )initWithFileExtension: ( NSString * )extension conformingTo: ( UTI * )uti;
- ( instancetype )initWithMIMEType: ( NSString * )type;
- ( instancetype )initWithMIMEType: ( NSString * )type conformingTo: ( UTI * )uti;
- ( instancetype )initWithNSPboardType: ( NSString * )type;
- ( instancetype )initWithNSPboardType: ( NSString * )type conformingTo: ( UTI * )uti;
- ( instancetype )initWithOSType: ( NSString * )type;
- ( instancetype )initWithOSType: ( NSString * )type conformingTo: ( UTI * )uti;
- ( instancetype )initWithTag: ( NSString * )tag tagClass: ( UTITagClass )tagClass conformingTo: ( UTI * )uti NS_DESIGNATED_INITIALIZER;
- ( NSString * )preferredTagForTagClass: ( UTITagClass )tagClass;
- ( BOOL )isEqualToUTI: ( UTI * )uti;
- ( BOOL )conformsToUTI: ( UTI * )uti;
- ( id )objectForDeclarationDictionaryKey: ( UTIDeclarationDictionaryKey )key;

@end
